### ISSUE TITLE
Compatibility test with Apple homepod

### ISSUE THREAD

**Issue by sangsoolee** [Samsung/ioter#23]
Compatibility test with Apple homepod.
If no problem, add it to README as a compatible device

**Comment by ejunu** [comment]
We confirmed that ioter works on the apple homepod, and updated the README.

https://github.com/Samsung/ioter/pull/72

**Comment by sangsoolee** [comment]
not merged yet

**Comment by sangsoolee** [comment]
https://github.com/Samsung/ioter/pull/72
