### ISSUE TITLE
[BUG] Humidity Sensor icon mismatch

### ISSUE THREAD

**Issue by spdkimo** [Samsung/ioter#29]
There is an icon that Humidity Sensor is shown in the device search on SmartThings. But a icon on a device card created after onboarding is different from the previous one

**Comment by junyong-sim** [comment]
When I've checked ST device app, icon mistach happened, too.

**Comment by jinwon0325kim** [comment]
It seems to be ST app issue.
If register as a Samsung humidity sensor, the icon displayed as the matter default icon.
