### ISSUE TITLE
The adjustment value of the slide bar of the light sensor is abnormal.

### ISSUE THREAD

**Issue by gdinolee** [Samsung/ioter#75]
The adjustment value of the slide bar of the light sensor is abnormal.
The amount of change between the front and back is too different.

**Comment by spdkimo** [comment]
The slide bar changes a range within from 1 to 0xfffe. And the value is converted to an exponential of 10 and represents to 1 through 3576000. The formula used follows from the Matter specification.

**Comment by spdkimo** [comment]
Even if MaxMeasuredValue is set, SmartThings set the max value to 100000 on its UI.
I will change Max value on ioter like SmartThings
