### ISSUE TITLE
The doorlock device has diffrent look and feel from other devices.

### ISSUE THREAD

**Issue by junyong-sim** [Samsung/ioter#88]
After onboarding was completed, the doorlock device has diffrent look and feel from other devices.

![light](https://github.com/Samsung/ioter/assets/38707627/18584e51-dbdf-4d01-a6c2-ce4cb5324177)
![doorlock](https://github.com/Samsung/ioter/assets/38707627/86298072-809c-4337-8408-21fb25118e06)

**Comment by spdkimo** [comment]
Since UI improvement is prepared, you need to test with it
https://github.com/Samsung/ioter/pull/76

**Comment by junyong-sim** [comment]
> Since UI improvement is prepared, you need to test with it #76

oh, great ! Thanks.

**Comment by junyong-sim** [comment]
https://github.com/Samsung/ioter/pull/76
